# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
  replicaCount: 2
  image:
    repository: cloudacademydevops/frontend
    tag: v11
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: LoadBalancer
    port: 80

api:
  replicaCount: 2
  image:
    repository: cloudacademydevops/api
    tag: v3
    pullPolicy: IfNotPresent

  service:
    name: api-service
    type: LoadBalancer
    port: 8080

mongodb:
  replicaCount: 3
  image:
    repository: mongo:4.2
    tag: latest
    pullPolicy: IfNotPresent

  service:
    name: mongodb-service
    type: ClusterIP
    port: 27017

resources: {}
